# Generated by Django 6.0.4 on 2026-04-28 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('medical_record_number', models.CharField(max_length=64, unique=True)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Unspecified')], default='unspecified', max_length=16)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('insurance_number', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
    ]
